### ISSUE TITLE
new so i may just be an idiot

### ISSUE THREAD

**Issue by zkapp14** [nmlynch94/com.jagexlauncher.JagexLauncher#22]
the instalation worked, the app is in my linux apps folder and has the green download needed icon, however it has been downloading for an excessive amount of time. Did i do something wrong possibly in the installation or is it just my computers processing power being a slow download that needs excessive time to download. 
for context, i opened the jagex launcher and it has been "opening/downloading"(spinning icon) for a little over an hour. newer to linux so i apologize i may just be an idiot.

**Comment by nmlynch94** [comment]
No problem we’ll get you straightened out. Can you run “flatpak run com.jagex.JagexLauncher” in your terminal and post the logs here?

**Comment by zkapp14** [comment]
![Screenshot 2024-02-10 3 29 10 PM](https://github.com/nmlynch94/com.jagexlauncher.JagexLauncher/assets/159654091/8bfae917-7f16-4243-a401-7542566e0041)
ok this makes me think i fd up somewhere...

**Comment by zkapp14** [comment]
![Screenshot 2024-02-10 3 29 57 PM](https://github.com/nmlynch94/com.jagexlauncher.JagexLauncher/assets/159654091/dd20d54e-ecb1-4807-96d9-3c609d69ade7)
here is the launcher downloading icon

**Comment by nmlynch94** [comment]
Apologies, I made a typo. flatpak run com.jagexlauncher.JagexLauncher

**Comment by zkapp14** [comment]
![Screenshot 2024-02-10 3 35 22 PM](https://github.com/nmlynch94/com.jagexlauncher.JagexLauncher/assets/159654091/58ea1ec4-5166-4bd9-8aaa-89f3156dcad1)
this is what i get here and no need to apologize im the new one wasting your time XD

**Comment by nmlynch94** [comment]
Not a waste of time! That’s what the issues section is for haha. Are you by chance on a raspberrypi or something? It looks like it’s trying to run the aarch64 version of the flatpak, which won’t work.

**Comment by zkapp14** [comment]
im on a chromebook that i had to download linux and linux terminal on, so im not..sure..to be honest....attached photo of the terminal opening if that helps? does this mean i need a different version of the flatpack?
![Screenshot 2024-02-10 3 42 09 PM](https://github.com/nmlynch94/com.jagexlauncher.JagexLauncher/assets/159654091/be52a966-b8d2-4b15-90cd-6f1be07cba76)

**Comment by nmlynch94** [comment]
Ah, ok yeah that’s the issue then. Your hardware architecture is incompatible with this flatpak. The good news is, you should be able to use the Bolt Launcher. flatpak install com.adamcake.Bolt. If it won’t launch, try flatpak run com.adamcake.Bolt --no-sandbox. I think you’ll only be able to play RuneLite if it works bc RuneScape isn’t built for that architecture.

**Comment by zkapp14** [comment]
![Screenshot 2024-02-10 3 48 04 PM](https://github.com/nmlynch94/com.jagexlauncher.JagexLauncher/assets/159654091/113c94d4-d8f6-4ce3-b375-b13873d4a2d7)
is this what you mean?

**Comment by zkapp14** [comment]
![Screenshot 2024-02-10 3 51 14 PM](https://github.com/nmlynch94/com.jagexlauncher.JagexLauncher/assets/159654091/681eced1-5119-456c-a408-b71523e23124)
i may have to find a new installation for it, thank you for the help though

**Comment by nmlynch94** [comment]
Ok that’s an error that we have seen on Chromebooks before. I think it has a fix, but you’d want to join the discord and ask for help bc im mobile and can’t find the instructions right now. Your call, but on Chromebook Bolt Launcher will be your only option to use the jagex launcher that I’m aware of.

**Comment by zkapp14** [comment]
i am in the discord so that works out i appreciate the help that youve been able to give me :)
