### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by VlaK0r** [nmlynch94/com.jagexlauncher.JagexLauncher#27]
Hello!
Thank you for your hard work!
Please tell me how to delete everything that was installed?

**Comment by ghost** [comment]
Not owner, but it's in the readme:

> flatpak remove --delete-data com.jagexlauncher.JagexLauncher

**Comment by nmlynch94** [comment]
The above is correct. This is just a flatpak and can be managed with the flatpak cli or your distro's software center if it supports it. Closing.
