### ISSUE TITLE
Launcher Won't Run After Installing NVIDIA Drivers

### ISSUE THREAD

**Issue by dbalaban** [nmlynch94/com.jagexlauncher.JagexLauncher#28]
I had this working, but the game was running very slowly, realized the graphics drivers weren't installed, after installing nvidia drivers hoping the game would use the GPU for a speed-up, the launcher gives the message to check connection and try re-launching. I assume it's referencing an internet connection, but my internet is working fine. Is it unable to connect to the GPU?

**Comment by Prolebox** [comment]
Fresh installation of Linux Mint with i9-13900ks and Nvidia 4090 and I had this same issue. Running "flatpak run com.jagexlauncher.JagexLauncher " several times seems to have worked. If I run into the issue again I'll upload logs.

**Comment by nmlynch94** [comment]
> I had this working, but the game was running very slowly, realized the graphics drivers weren't installed, after installing nvidia drivers hoping the game would use the GPU for a speed-up, the launcher gives the message to check connection and try re-launching. I assume it's referencing an internet connection, but my internet is working fine. Is it unable to connect to the GPU?

I tried once yesterday and also had an issue launching. Today I tried to reproduce to fix it and now it's working. I did a quick check so not sure if I just didn't test properly prior or if the reboot knocked something loose. 

Could you please try a flatpak update followed by a reboot and then see if that fixes it? 

Please run it via the cli `flatpak run com.jagexlauncher.JagexLauncher` so and post logs here if it breaks.

**Comment by nmlynch94** [comment]
@dbalaban I've made some updates. Could you please try `flatpak remove --delete-data com.jagexlauncher.JagexLauncher` and then try the installation script in the readme?

I suspect you're missing the flatpak version of your nvidia drivers, and the updated installation script will add that for you.

**Comment by nmlynch94** [comment]
Assuming this is resolved. Feel free to ask to reopen if not.

**Comment by Retalak** [comment]
> DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
0340:fixme:thread:QueryThreadCycleTime (00000148,0345FE18): stub!
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
0238:err:d3d:wined3d_caps_gl_ctx_create Failed to find a suitable pixel format.
0238:err:d3d:wined3d_adapter_gl_init Failed to get a GL context for adapter 00FBA8F0.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
0238:err:d3d:wined3d_caps_gl_ctx_create Failed to find a suitable pixel format.
0238:err:d3d:wined3d_adapter_gl_init Failed to get a GL context for adapter 00FBDFA8.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
0238:err:d3d:wined3d_caps_gl_ctx_create Failed to find a suitable pixel format.
0238:err:d3d:wined3d_adapter_gl_init Failed to get a GL context for adapter 00FBDFA8.
0348:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
0228:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
0338:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
01ac:fixme:winstation:GetUserObjectSecurity (00000050 06BCF7DC 00000000 len=0 06BCF7E0),stub!
01ac:fixme:winstation:GetUserObjectSecurity (00000050 06BCF7DC 52C630F0 len=20 06BCF7E0),stub!
01ac:fixme:ntdll:NtSetInformationToken TokenIntegrityLevel stub!
01ac:fixme:ntdll:NtFilterToken flags 0x1 unsupported
01ac:fixme:ntdll:NtFilterToken support for restricting sids not yet implemented
01ac:fixme:advapi:SetEntriesInAclW unhandled access mode 4
01ac:fixme:ntdll:NtFilterToken support for restricting sids not yet implemented
01ac:fixme:advapi:SetEntriesInAclW unhandled access mode 4
01ac:fixme:sync:NtSetInformationJobObject stub: 0x328 4 0x6bcf75c 4
01ac:fixme:process:GetProcessMitigationPolicy (FFFFFFFF, 5, 005F68F0, 16): stub
01ac:fixme:process:UpdateProcThreadAttribute Unhandled attribute 26
01ac:fixme:process:CreateProcessInternalW Unsupported attribute 0x2000e.
01ac:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenAppContainerSid, ...) semi-stub
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
01b8:fixme:ver:GetFileVersionInfoSizeExW flags 0x2 ignored
01b8:fixme:ver:GetFileVersionInfoExW flags 0x2 ignored
01b8:fixme:ver:GetFileVersionInfoSizeExW flags 0x2 ignored
01b8:fixme:ver:GetFileVersionInfoExW flags 0x2 ignored
01b8:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
01b8:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
01b8:fixme:heap:RtlSetHeapInformation HEAP_INFORMATION_CLASS 1 not implemented!
01b8:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 5C068268, 16) stub
01b8:fixme:process:GetProcessMitigationPolicy (FFFFFFFF, 4, 0082C014, 4): stub
01b8:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
01b8:err:wgl:X11DRV_WineGL_InitOpenglInfo  couldn't initialize OpenGL, expect problems
01b8:err:d3d:wined3d_caps_gl_ctx_create Failed to find a suitable pixel format.
01b8:err:d3d:wined3d_adapter_gl_init Failed to get a GL context for adapter 00EF9C60.
01b8:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
0318:fixme:thread:QueryThreadCycleTime (00000148,033BFE18): stub!
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
01b8:err:d3d:wined3d_caps_gl_ctx_create Failed to find a suitable pixel format.
01b8:err:d3d:wined3d_adapter_gl_init Failed to get a GL context for adapter 00F1A8F0.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
01b8:err:d3d:wined3d_caps_gl_ctx_create Failed to find a suitable pixel format.
01b8:err:d3d:wined3d_adapter_gl_init Failed to get a GL context for adapter 00F1DFA8.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
01b8:err:d3d:wined3d_caps_gl_ctx_create Failed to find a suitable pixel format.
01b8:err:d3d:wined3d_adapter_gl_init Failed to get a GL context for adapter 00F1DFA8.
0354:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
0398:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
018c:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
01ac:fixme:winstation:GetUserObjectSecurity (00000050 06BCF7DC 00000000 len=0 06BCF7E0),stub!
01ac:fixme:winstation:GetUserObjectSecurity (00000050 06BCF7DC 52C65568 len=20 06BCF7E0),stub!
01ac:fixme:ntdll:NtSetInformationToken TokenIntegrityLevel stub!
01ac:fixme:ntdll:NtFilterToken flags 0x1 unsupported
01ac:fixme:ntdll:NtFilterToken support for restricting sids not yet implemented
01ac:fixme:advapi:SetEntriesInAclW unhandled access mode 4
01ac:fixme:ntdll:NtFilterToken support for restricting sids not yet implemented
01ac:fixme:advapi:SetEntriesInAclW unhandled access mode 4
01ac:fixme:sync:NtSetInformationJobObject stub: 0x214 4 0x6bcf75c 4
01ac:fixme:process:GetProcessMitigationPolicy (FFFFFFFF, 5, 005F68F0, 16): stub
01ac:fixme:process:UpdateProcThreadAttribute Unhandled attribute 26
01ac:fixme:process:CreateProcessInternalW Unsupported attribute 0x2000e.
01ac:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenAppContainerSid, ...) semi-stub
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
0364:fixme:ver:GetFileVersionInfoSizeExW flags 0x2 ignored
0364:fixme:ver:GetFileVersionInfoExW flags 0x2 ignored
0364:fixme:ver:GetFileVersionInfoSizeExW flags 0x2 ignored
0364:fixme:ver:GetFileVersionInfoExW flags 0x2 ignored
0364:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0364:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0364:fixme:heap:RtlSetHeapInformation HEAP_INFORMATION_CLASS 1 not implemented!
0364:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 2C268268, 16) stub
0364:fixme:process:GetProcessMitigationPolicy (FFFFFFFF, 4, 0082C014, 4): stub
0364:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!


Occurring on Arch after updating today. This is spammed over and over and then eventually I get the check your connection pop up.

**Comment by Retalak** [comment]
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > 0340:fixme:thread:QueryThreadCycleTime (00000148,0345FE18): stub!
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > 0238:err:d3d:wined3d_caps_gl_ctx_create Failed to find a suitable pixel format.
> > 0238:err:d3d:wined3d_adapter_gl_init Failed to get a GL context for adapter 00FBA8F0.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > 0238:err:d3d:wined3d_caps_gl_ctx_create Failed to find a suitable pixel format.
> > 0238:err:d3d:wined3d_adapter_gl_init Failed to get a GL context for adapter 00FBDFA8.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > 0238:err:d3d:wined3d_caps_gl_ctx_create Failed to find a suitable pixel format.
> > 0238:err:d3d:wined3d_adapter_gl_init Failed to get a GL context for adapter 00FBDFA8.
> > 0348:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
> > 0228:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
> > 0338:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
> > 01ac:fixme:winstation:GetUserObjectSecurity (00000050 06BCF7DC 00000000 len=0 06BCF7E0),stub!
> > 01ac:fixme:winstation:GetUserObjectSecurity (00000050 06BCF7DC 52C630F0 len=20 06BCF7E0),stub!
> > 01ac:fixme:ntdll:NtSetInformationToken TokenIntegrityLevel stub!
> > 01ac:fixme:ntdll:NtFilterToken flags 0x1 unsupported
> > 01ac:fixme:ntdll:NtFilterToken support for restricting sids not yet implemented
> > 01ac:fixme:advapi:SetEntriesInAclW unhandled access mode 4
> > 01ac:fixme:ntdll:NtFilterToken support for restricting sids not yet implemented
> > 01ac:fixme:advapi:SetEntriesInAclW unhandled access mode 4
> > 01ac:fixme:sync:NtSetInformationJobObject stub: 0x328 4 0x6bcf75c 4
> > 01ac:fixme:process:GetProcessMitigationPolicy (FFFFFFFF, 5, 005F68F0, 16): stub
> > 01ac:fixme:process:UpdateProcThreadAttribute Unhandled attribute 26
> > 01ac:fixme:process:CreateProcessInternalW Unsupported attribute 0x2000e.
> > 01ac:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenAppContainerSid, ...) semi-stub
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > 01b8:fixme:ver:GetFileVersionInfoSizeExW flags 0x2 ignored
> > 01b8:fixme:ver:GetFileVersionInfoExW flags 0x2 ignored
> > 01b8:fixme:ver:GetFileVersionInfoSizeExW flags 0x2 ignored
> > 01b8:fixme:ver:GetFileVersionInfoExW flags 0x2 ignored
> > 01b8:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
> > 01b8:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
> > 01b8:fixme:heap:RtlSetHeapInformation HEAP_INFORMATION_CLASS 1 not implemented!
> > 01b8:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 5C068268, 16) stub
> > 01b8:fixme:process:GetProcessMitigationPolicy (FFFFFFFF, 4, 0082C014, 4): stub
> > 01b8:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > 01b8:err:wgl:X11DRV_WineGL_InitOpenglInfo  couldn't initialize OpenGL, expect problems
> > 01b8:err:d3d:wined3d_caps_gl_ctx_create Failed to find a suitable pixel format.
> > 01b8:err:d3d:wined3d_adapter_gl_init Failed to get a GL context for adapter 00EF9C60.
> > 01b8:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > 0318:fixme:thread:QueryThreadCycleTime (00000148,033BFE18): stub!
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > 01b8:err:d3d:wined3d_caps_gl_ctx_create Failed to find a suitable pixel format.
> > 01b8:err:d3d:wined3d_adapter_gl_init Failed to get a GL context for adapter 00F1A8F0.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > 01b8:err:d3d:wined3d_caps_gl_ctx_create Failed to find a suitable pixel format.
> > 01b8:err:d3d:wined3d_adapter_gl_init Failed to get a GL context for adapter 00F1DFA8.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > 01b8:err:d3d:wined3d_caps_gl_ctx_create Failed to find a suitable pixel format.
> > 01b8:err:d3d:wined3d_adapter_gl_init Failed to get a GL context for adapter 00F1DFA8.
> > 0354:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
> > 0398:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
> > 018c:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
> > 01ac:fixme:winstation:GetUserObjectSecurity (00000050 06BCF7DC 00000000 len=0 06BCF7E0),stub!
> > 01ac:fixme:winstation:GetUserObjectSecurity (00000050 06BCF7DC 52C65568 len=20 06BCF7E0),stub!
> > 01ac:fixme:ntdll:NtSetInformationToken TokenIntegrityLevel stub!
> > 01ac:fixme:ntdll:NtFilterToken flags 0x1 unsupported
> > 01ac:fixme:ntdll:NtFilterToken support for restricting sids not yet implemented
> > 01ac:fixme:advapi:SetEntriesInAclW unhandled access mode 4
> > 01ac:fixme:ntdll:NtFilterToken support for restricting sids not yet implemented
> > 01ac:fixme:advapi:SetEntriesInAclW unhandled access mode 4
> > 01ac:fixme:sync:NtSetInformationJobObject stub: 0x214 4 0x6bcf75c 4
> > 01ac:fixme:process:GetProcessMitigationPolicy (FFFFFFFF, 5, 005F68F0, 16): stub
> > 01ac:fixme:process:UpdateProcThreadAttribute Unhandled attribute 26
> > 01ac:fixme:process:CreateProcessInternalW Unsupported attribute 0x2000e.
> > 01ac:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenAppContainerSid, ...) semi-stub
> > DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> > 0364:fixme:ver:GetFileVersionInfoSizeExW flags 0x2 ignored
> > 0364:fixme:ver:GetFileVersionInfoExW flags 0x2 ignored
> > 0364:fixme:ver:GetFileVersionInfoSizeExW flags 0x2 ignored
> > 0364:fixme:ver:GetFileVersionInfoExW flags 0x2 ignored
> > 0364:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
> > 0364:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
> > 0364:fixme:heap:RtlSetHeapInformation HEAP_INFORMATION_CLASS 1 not implemented!
> > 0364:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 2C268268, 16) stub
> > 0364:fixme:process:GetProcessMitigationPolicy (FFFFFFFF, 4, 0082C014, 4): stub
> > 0364:fixme:thread:NtSetInformationThread ThreadPowerThrottling stub!
> 
> Occurring on Arch after updating today. This is spammed over and over and then eventually I get the check your connection pop up.

Reinstalling as described does seem to have resolved this.
